### ISSUE TITLE
Error when running solutions for Unit-6

### ISSUE THREAD

**Issue by rikort** [jstevenperry/IBM-Developer#14]
When running the solution for Unit-6, the following error occurs:

1564236974967:ERROR: testItemFindById(): TEST FAILED. Try again.
1564236974968:ERROR: testItemFindById(): ERROR MESSAGE: Assert failed: actual => Mueller Sport Care Basic Support Level Medium Elastic Knee Support, expected => Lea & Perrins Marinade In-a-bag Cracked Peppercorn.
(node:43705) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: Assert failed: actual => Mueller Sport Care Basic Support Level Medium Elastic Knee Support, expected => Lea & Perrins Marinade In-a-bag Cracked Peppercorn
    at assertEqual (/Users/rickortega/IBM-Developer/Node.js/Course/Unit-6/utils/utils.js:146:12)
    at request (/Users/rickortega/IBM-Developer/Node.js/Course/Unit-6/test/functional-test.js:151:21)
    at IncomingMessage.response.on (/Users/rickortega/IBM-Developer/Node.js/Course/Unit-6/test/functional-test.js:68:17)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:43705) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:43705) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jstevenperry** [comment]
Sorry for the trouble you're having. Nothing is more frustrating than when the "solution" doesn't work. I get it. So sorry about that.

I have confirmed the functional test is broken, most likely due to changes in the sqlite3 package and the order in which it loads and auto-assigns IDs to the rows at creates them. 

I have updated package.json to pull in the latest (4.0.9) sqlite3 package, and corrected the issue with the functional test, and it works for me now. Please pull the latest code, and run the functional test again. I will leave this issue open for a while to give you the chance to comment if it doesn't work.

I am using Node 8.12.0 and npm 6.4.1, FYI.

If it still doesn't work for you, please tell me the versions of node and npm you're using so I can try and duplicate on my end.

Thanks for reporting this, and thanks for reading!

**Comment by rikort** [comment]
It works perfectly and I am learning by the minute! Thank you so much!
